version: 2

updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly

  - package-ecosystem: gitsubmodule
    schedule:
      interval: "daily"
    directory: /
